### ISSUE TITLE
alter sketch for 6 button input?

### ISSUE THREAD

**Issue by grandmasterazz** [Dadie/Arduino-SEGA-Mega-Drive-2-Player-Controller#1]
hi there...
am fairly new to arduino... have tried a few changes and cant get the code to change to register a 6 button sega mega drive gamepad? please help... thanks :)

**Comment by Dadie** [comment]
Sorry for the  inconvenience, to be honest, I had not yet tested the code on a 6-Button controller (has I had none) ^^. the code to detect 6-Button and interact with them was done purely of the information from [segaretro](http://segaretro.org/Six_Button_Control_Pad_(Mega_Drive)).

I asked around and got a few controllers (some from 3rd-party vendors some from Sega)  and indeed each one has it's own bug (and doesn't seem to work right). I'll try to figure out how to make them all work right :)

**Comment by Dadie** [comment]
Okay... that took way longer then I anticipated. The first few 6-Button Controllers I got my hands on where weird. I just could not get them to work right. So I had to confirm whether or not they worked normal on a Mega Drive at all. So to test this I first had to get a 6-Button Mega Drive game. Took me a while to buy one (only to realize I had one since the beginning...). With **two** 6-Button games I confirmed they were all broken *doh*. Then I had to find 6-Button Controllers that worked on the Mega Drive. And just recently I had luck on eBay and found working 6-Button Controllers.

The commit 4ea84139e09252c1537f29e7d1449fca776405ba should finally fix all problems with 6-Button Controllers.
